{% set name = "ravenpy" %}
{% set version = "0.12.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: cc932b236a9a5173609f744a19539e72ee51ccf635d41a7f1e61c3f771daa1f0

build:
  number: 2
  script: {{ PYTHON }} -m pip install . -vv
  script_env:
    - CONDA_BUILD

requirements:
  host:
    - python
    - flit
    - pip
  run:
    - raven-hydro ==0.2.1
    - python
    - cf_xarray
    - cftime
    - click >=8.0.0
    - climpred >=2.3
    - dask
    - fiona >=1.9
    - gdal >=3.0
    - geopandas >=0.13
    - haversine
    - lxml
    - matplotlib-base
    - netcdf4
    - numpy
    - owslib >=0.24.1,<0.29
    - pandas <2.0  # [py==38]
    - pandas  # [py>=39]
    - pint >=0.20
    - pydantic >=1.10.8
    - pymbolic
    - pyproj >=3.0.0
    - rasterio
    - requests
    - rioxarray
    - scipy >=1.6.3
    - shapely
    - spotpy
    - statsmodels
    - xarray
    - xclim >=0.43.0
    - xskillscore

test:
  requires:
    - pip
  imports:
    - ravenpy
  commands:
    - raven -v
    - pip check

about:
  home: https://github.com/CSHS-CWRA/RavenPy
  dev_url: https://github.com/CSHS-CWRA/RavenPy
  doc_url: https://ravenpy.readthedocs.io/en/latest/
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: A Python wrapper to setup and run the hydrologic modelling framework Raven.

extra:
  recipe-maintainers:
    - huard
    - Zeitsperre
    - cjauvin
