{% set name = "ravenpy" %}
{% set version = "0.5.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 5193bac524b099f00f3a9ef496dd8397592ca705945830c505a7f20ccd353aeb

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.7
    - setuptools
    - numpy
    - gdal
    - pip
  run:
    - raven-hydro ==3.0.4.322
    - ostrich ==21.03.16
    - python >=3.7
    - cftime
    - cf_xarray
    - click >7
    - climpred >=2.1
    - clisops >=0.6.3
    - fiona
    - gdal
    - geopandas >=0.9
    - netcdf4
    - lxml
    - matplotlib-base
    - numpy
    - owslib
    - pandas >=1.2
    - pydantic
    - pyproj >=3
    - rasterio
    - requests
    - rioxarray
    - scipy >=1.6.3
    - shapely
    - statsmodels
    - xarray ==0.18
    - xclim >=0.26.1

test:
  imports:
    - ravenpy
  commands:
    - raven -v

about:
  home: https://github.com/CSHS-CWRA/RavenPy
  dev_url: https://github.com/CSHS-CWRA/RavenPy
  doc_url: https://ravenpy.readthedocs.io/en/latest/
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: A Python wrapper to setup and run the hydrologic modelling framework Raven.

extra:
  recipe-maintainers:
    - Zeitsperre
    - cjauvin
